apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-weather
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: weatherapp-weather
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weatherapp-weather
    spec:
      containers:
      - name: weatherapp-weather
        image: salemaljebaly/weatherapp-weather:lab
        imagePullPolicy: IfNotPresent
        env:
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: weather
              key: apikey
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
