apiVersion: v1
kind: Service
metadata:
  name: weatherapp-weather
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: http
  selector:
    app.kubernetes.io/name: weatherapp-weather